# base
dir: tmp
seed: 0
log_wandb: online
log_interval: 10
log_interval_ste: 500

# data
data: cifar10
num_classes: 10

# model
model: resnet20
width_multiplier: 16
amp: True

model_a: cifar10_split_a
model_b: cifar10_split_b
a_v: 4
b_v: 2
a_epoch: 100
b_epoch: 100

# train
batch_size: 100
epoch: 1000
opt: sgd
weight_decay: 1e-4
lr: 0.1
lr_schedule: warmup_cosine_decay
warmup_epoch: 1
train_data_type: data_cond
# https://github.com/VICO-UoE/DatasetCondensation/blob/master/main.py#L25
epoch_dc: 600
batch_size_dc: 100
opt_dc: sgd
lr_dc: 0.1
lr_schedule_dc: cosine
ipc: 50
#cond_a: data/DatasetCondensation/kip/kip_cifar10_ConvNet_ssize10_nozca_l_noaug_ckpt44000.npz 
cond_a: data/DatasetCondensation/kip/kip_cifar10_ConvNet_ssize500_nozca_nol_noaug_ckpt11500.npz
cond_b: None
repair: True

