# base
dir: tmp
seed: 0
log_wandb: online
log_interval: 10
log_interval_ste: 500

# data
data: cifar10
num_classes: 10

# model
model: resnet20
width_multiplier: 16
amp: True

model_a: cifar10_split_a
model_b: cifar10_split_b
a_v: 4
b_v: 2
a_epoch: 100
b_epoch: 100

# train
batch_size: 250 # 500
epoch: 100
opt: sgd
weight_decay: 1e-4
lr: 1
lr_schedule: warmup_cosine_decay
warmup_epoch: 1
train_data_type: full
repair: True
