# base
dir: tmp
seed: 0
log_wandb: online
log_interval: 5
log_interval_ste: 100

# data
data: usps_mnist
num_classes: 10
trans_type: color_32

# model
model: mlp
bias: True
model_a: mnist
model_b: usps
a_v: 4
b_v: 4
a_epoch: 100
b_epoch: 100

# train
batch_size: 500
epoch: 50
opt: sgd
weight_decay: 1e-4
lr: 0.5
warmup_epoch: 0
train_data_type: full

