# base
dir: tmp
seed: 0
log_wandb: online
log_interval: 10
log_interval_ste: 100

# data
data: mnist_fmnist
num_classes: 10

# model
model: mlp
bias: True
model_a: mnist
model_b: fmnist
a_v: 1
b_v: 0
a_epoch: 100
b_epoch: 100

# train
batch_size: 500
epoch: 5000
opt: sgd
weight_decay: 1e-4
lr: 0.5
lr_schedule: multi_step_lr
warmup_epoch: 0
train_data_type: coreset
epoch_dc: 200
batch_size_dc: 500
opt_dc: sgd
lr_dc: 0.05
ipc: 10
cond_a: data/CoreSelection/mlp/None/MNIST_MLP_Glister.pt
cond_b: data/CoreSelection/mlp/None/FashionMNIST_MLP_Glister.pt
