# base
dir: tmp
seed: 0
log_wandb: online
log_interval: 10
log_interval_ste: 100

# data
data: mnist_rotated_mnist_60
num_classes: 10

# model
model: mlp
bias: True
model_a: mnist
model_b: rotated_mnist_60
a_v: 1
b_v: 0
a_epoch: 100
b_epoch: 100

# train
batch_size: 500
epoch: 1000
opt: sgd
weight_decay: 1e-4
lr: 0.1
lr_schedule: multi_step_lr
warmup_epoch: 0
train_data_type: data_cond
epoch_dc: 200
batch_size_dc: 500
opt_dc: sgd
lr_dc: 0.01
ipc: 1
cond_a: data/DatasetCondensation/mlp/rotated/res_DC_rotated_mnist_0_MLP_1ipc.pt
cond_b: data/DatasetCondensation/mlp/rotated/res_DC_rotated_mnist_60_MLP_1ipc.pt