# base
dir: tmp
seed: 0
log_wandb: online

# data
data: mnist_rotated_mnist_60
num_classes: 10

# model
model: mlp
bias: True
model_a: mnist
model_b: rotated_mnist_60
a_v: 1
b_v: 0
a_epoch: 100
b_epoch: 100


# train
batch_size: 500
